books/urls.py
from django.urls import path

from books.views import listview

app_name = 'books'

urlpatterns = [

    path("books/", listview, name='list'),

]

examples/urls.py
from django.contrib import admin
from django.urls import path, include

from books.views import listview



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("books.urls")),
    path("posts/", include("posts.urls")),

]

main/urls.py
from django.urls import path

from .views import homepage, greetings

urlpatterns = [
    path("", homepage, name='home_test'),
    path("greetings/", greetings),



]

posts/urls.py
from django.urls import path

from posts.views import listview

app_name = 'posts'

urlpatterns = [

    path("", listview, name='list'),


]

books/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.

books/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def listview(request):
    return render(
        request,
        "books/books_template.html",
        {"dane": "Dane: Lista ksiazek, ksiazkowe informacje"}
    )

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

# Create your views here.

def homepage(request):
    #template = loader.get_template("homepage.html")
    #contex = {}
    #return HttpResponse(template.render(contex, request))

    return render(
        request,
        "main/homepage.html",
        {"dane": "ALA MA KOTA"}

    )


def greetings(request):
    return  HttpResponse("Hello!!!")

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def listview(request):
    return render(
        request,
        "posts/posts_template.html",
        {"dane": "Dane: Lista postow, cos o postach"}
    )

books/templates/books/books_template.html
{% extends 'base.html' %}

{% block title %} LISTA KSIAŻEK (extends)  {% endblock %}

{% block content %}
<h1> Lista książek </h1>

{% endblock %}

main/templates/main/homepage.html
{% extends 'base.html' %}
{% load books_extras %}

{% block title%} Main !! {{ block.super }}  {% endblock %}

{% block content %}
<h1> HOMEPAGE </h1>
<p> Szablon z aplikacji </p>

{{dane}}

{%for el in dane%} {# for to jest takze 'tag' #}
    <p> {{el}} </p>
{% endfor %}

    {{'jakis tekst'|upper}} <!-- Powieksza litery -->
<br>
    {{'Ala ma kota, kot ma Alę'|upper|truncatewords:"4"}}  <!-- Obcina tekst to zadanej wartosci słów -->

<br>
    {{"Dupa JASIU"|to_lower }}

    <br>

    {{"ABRAKADABRA LEWE OKO PROROKA"|to_lower|cut:"lewe"}}  <!-- CUT - to nasz custom filter  -->

    <br>

     {% current_time %}

{% endblock %}

posts/templates/includes/footer.html
<footer> Stopka strony poprawiony
    <ul>
   <li><a href="/"> Home </a>
    <li><a href="/posts/"> Blog </a>
    <li><a href="/books/"> Library </a></li>

    </ul>
</footer>

posts/templates/includes/header.html
<!--
<header class="row">

    <a href="{% url 'home_test'  %}" class="col-lg-4 col-sm-12"> Home </a> |
    <a href="{% url 'posts:list'  %}" class="col-lg-4 col-sm-12"> Blog </a> |
    <a href="{% url 'books:list'  %}" class="col-lg-4 col-sm-12"> Library </a>


</header>
-->

<!-- Grey with black text -->
<nav class="navbar navbar-expand-sm bg-success navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'home_test'  %}">Home</a>
      </li>
     <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:list'  %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'books:list'  %}">Library</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

posts/templates/posts/posts_template.html
{% extends 'base.html' %}

{% block title %} LISTA POSTOW {% endblock %}

{% block content %}
<h1> Lista postów </h1>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {%block title%} {% endblock %}  </title>
   <!-- CSS only -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style>
        .pochyly {
        font-style: oblique;
        }
    </style>


    </style>
</head>
<body>
{% include 'includes/header.html' %}

<p>paragraf</p>
<p class="pochyly">paragraf klasy pochyly</p>

{% block content %}
{% endblock %}


{% include 'includes/footer.html' %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>